name: trendys_sdk
description: Trendys SDK
version: 0.0.1
author: developers@trendys.fr
homepage: https://github.com/trendys/sdk

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8
  flutter_secure_storage: ^3.3.3
  retrofit: ^1.3.4
  json_serializable: ^3.3.0
  jose: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
  build_runner:

flutter:
